[package]
name = "cnbc-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.39"
regex = "1.11.1"
reqwest = { version = "0.12.12", features = ["blocking", "rustls-tls"] }
scraper = "0.22.0"
serde_json = "1.0.135"